services:
  mysql:
    image: 'mysql:8.1'
    environment:
      - 'MYSQL_DATABASE=msorder'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=admin'
    ports:
      - '3306'
