
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
spring:
  application:
    name: msorder

  datasource:
    url: jdbc:mysql://localhost:3306/msorder
    username: admin
    password: 123456
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: org.mysql.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect